apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec: 
  ports:
    - port: 80
  selector:
    app: trading
    tier: app-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  labels:
    app: trading
spec: 
  selector:
    matchLabels:
      app: trading
      tier: app-server
  strategy:
    type: Recreate
  replicas: 2
  template: 
    metadata:
      labels:
        app: trading
        tier: app-server
    spec:
      containers:
      - image: jrvsregistry.azurecr.io/trading-app:latest
        name: trading-app
        ports:
        - containerPort: 80
          name: trading
